# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sowatch

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    A tool for using smart watches
Version:    0.1.0
Release:    1
Group:      Qt/Qt
License:    GPLv2
Source0:    %{name}-%{version}.tar.bz2
Source100:  sowatch.yaml
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)

%description
sowatch is a tool that allows you to use smart watches with your phone.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/opt/%{name}
%{_libdir}/lib%{name}*
%{_libdir}/%{name}
%{_includedir}/%{name}
%{_datadir}/%{name}
%{_bindir}/%{name}d
/opt/sowatch/bin
/usr/share/sowatch
/opt/sowatch/.
/usr/bin
/usr/lib
/usr/include/sowatch
/usr/share/sowatch/i18n
/usr/lib/sowatch/watchlets
/usr/share/sowatch/qml/notificationswatchlet
/usr/lib/sowatch/drivers
/usr/share/sowatch/metawatch
/usr/share/sowatch/qml
/usr/share/sowatch/qml/nekowatchlet
/usr/share/sowatch/qml/metawatchwatchlets
# >> files
# << files
