/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DaemonAdaptor -a daemonadaptor daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "daemonadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include "daemon.h"

/*
 * Implementation of adaptor class DaemonAdaptor
 */

DaemonAdaptor::DaemonAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DaemonAdaptor::~DaemonAdaptor()
{
    // destructor
}

QString DaemonAdaptor::GetWatchStatus(const QString &watch)
{
    // handle method call com.javispedro.sowatch.Daemon.GetWatchStatus
	return static_cast<sowatch::Daemon*>(parent())->getWatchStatus(watch);
}

void DaemonAdaptor::Terminate()
{
    // handle method call com.javispedro.sowatch.Daemon.Terminate
    static_cast<sowatch::Daemon*>(parent())->terminate();
}

