/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DaemonAdaptor -a daemonadaptor daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DAEMONADAPTOR_H_1335395583
#define DAEMONADAPTOR_H_1335395583

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.javispedro.sowatch.Daemon
 */
class DaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.javispedro.sowatch.Daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.javispedro.sowatch.Daemon\">\n"
"    <method name=\"GetWatchStatus\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"watch\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"Terminate\"/>\n"
"  </interface>\n"
        "")
public:
    DaemonAdaptor(QObject *parent);
    virtual ~DaemonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetWatchStatus(const QString &watch);
    void Terminate();
Q_SIGNALS: // SIGNALS
};

#endif
