/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ScannerAdaptor -a scanneradaptor scanner.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SCANNERADAPTOR_H_1335303169
#define SCANNERADAPTOR_H_1335303169

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.javispedro.sowatch.WatchScanner
 */
class ScannerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.javispedro.sowatch.WatchScanner")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.javispedro.sowatch.WatchScanner\">\n"
"    <method name=\"Start\"/>\n"
"    <signal name=\"Started\"/>\n"
"    <signal name=\"Finished\"/>\n"
"    <signal name=\"WatchFound\">\n"
"      <annotation value=\"QVariantMap\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a{sv}\" name=\"info\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ScannerAdaptor(QObject *parent);
    virtual ~ScannerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Start();
Q_SIGNALS: // SIGNALS
    void Finished();
    void Started();
    void WatchFound(const QVariantMap &info);
};

#endif
