/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ScannerAdaptor -a scanneradaptor scanner.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "scanneradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ScannerAdaptor
 */

ScannerAdaptor::ScannerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
	connect(parent, SIGNAL(started()), this, SIGNAL(Started()));
	connect(parent, SIGNAL(finished()), this, SIGNAL(Finished()));
	connect(parent, SIGNAL(watchFound(QVariantMap)),
	        this, SIGNAL(WatchFound(QVariantMap)));
}

ScannerAdaptor::~ScannerAdaptor()
{
    // destructor
}

void ScannerAdaptor::Start()
{
    // handle method call com.javispedro.sowatch.WatchScanner.Start
    QMetaObject::invokeMethod(parent(), "start");
}
